# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-07 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='avi_file',
        ),
        migrations.RemoveField(
            model_name='file',
            name='capture_file',
        ),
        migrations.RemoveField(
            model_name='file',
            name='log_file',
        ),
        migrations.AddField(
            model_name='file',
            name='LogFile',
            field=models.FileField(default='', upload_to='files'),
        ),
        migrations.AddField(
            model_name='file',
            name='VideoFile',
            field=models.FileField(default='', upload_to='files'),
        ),
    ]
