# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-07 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20171207_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdonUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nope', models.CharField(max_length=64)),
            ],
        ),
    ]
